#!/bin/sh
# 커밋 메시지가 "log: yyyy-mm-dd" 또는 "install: yyyy-mm-dd" 형식인지 검사
MESSAGE=$(cat $1)
if ! echo "$MESSAGE" | grep -Eq '^(log|install|fix): [0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
  echo "❌ 커밋 메시지는 'log: yyyy-mm-dd' 또는 'install: yyyy-mm-dd' 형식이어야 합니다."
  exit 1
fi
